### PR TITLE
fix: fix https://sapjira.wdf.sap.corp/browse/DEVXBUGS-6770

### PR DESCRIPTION
**Pull request by rayakoren**
Before submitting a pull request, please ensure the following:

## Description

Please explain the changes you made.

Add a link to the design (if applicable).

### Checklist

- [ ] Code compiles correctly
- [ ] Relevant tests were added (unit / contract / integration)
- [ ] Relevant logs were added
- [ ] Linting run locally successfully
- [ ] All tests pass
- [ ] UA review
- [ ] Design is documented
- [ ] Extended the README / documentation, if necessary
- [ ] Open source is approved

### CODE REVIEW

**Comment by lidortal** [comment]
This shouldn’t be handled by this extension. The system should be configured correctly. Fixing it here won’t solve deploying from the CLI.

**Comment by rayakoren** [comment]
> This shouldn’t be handled by this extension. The system should be configured correctly. Fixing it here won’t solve deploying from the CLI.

Deploying from CLI works for the user after he explicitly exports the DEPLOY_SERVICE_URL.
The problem of the user that the deploy to CF fails when he tries to deploy the mtar from the command. 
What do you mean by "the system should be configured correctly"? Is there a configuration that should solve this issue, if not, the command should work for the user as it works from the CLI, don't you think?

**Comment by lidortal** [comment]
If it works from the CLI then you should get the URL from env variable.

**Comment by michawai** [comment]
The purpose of wrapping 'cf deploy' is to make it simple for the end user.
From product view it is correct to set the env. variable for the end user.
This way the end user will have to click only the menu.

**Pull request closed without merging**
